name: my_thingsboard
services:
    tb-postgres:
        stdin_open: true
        tty: true
        ports:
            - 9090:9090
            - 1883:1883
            - 7070:7070
            - 5683-5688:5683-5688/udp
        volumes:
            - thingsboard_data:/data
            - thingsboard_logs:/var/log/thingsboard
        container_name: thingsboard
        restart: always
        image: thingsboard/tb-postgres
volumes:
    thingsboard_data:
    thingsboard_logs: